[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
cached = "0.26.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
nom = "7.1.0"
